[
    {
        "problem_type": "Type checking error",
        "language": "Python",
        "filename": "mergify_shadow_office/clients/loops.py",
        "lineno": "187",
        "error": "arg-type",
        "test_framework": "mypy",
        "stack_trace": "mergify_shadow_office/clients/loops.py:187: error: Argument 1 to \"to_isoformat\" has incompatible type \"datetime | None\"; expected \"date | datetime\""
    }
]