[
    {
        "problem_type": "Assertion Error",
        "test_name": "test_event_as_dict",
        "language": "Python",
        "filename": "mergify_engine/tests/unit/test_events_db.py",
        "lineno": 760,
        "error": "AssertionError",
        "test_framework": "pytest",
        "stack_trace": "assert {'deleted_by'...t': None, ...} == {'deleted_by'...t': None, ...}"
    }
]
